language: php

php:
    - 5.5
    - 5.6
    
service:
    -mysql
    
before_install:
    - wget http://getcomposer.org/composer.phar    
    # add ldap extension to php.ini
    - echo "extension=ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
    - mysql -e 'create database symfony;'
    - php composer.phar install --dev
    - pyrus install pear/PHP_CodeSniffer
    - phpenv rehash
    - php app/console doctrine:schema:update --force

script: 
    - phpunit --coverage-text -c app/phpunit.xml.dist 
    - phpcs --extensions=php --standard=PSR2 src

notifications:
  email:
    - jd.labails@gmail.com
