personne:
    path:     /
    defaults: { _controller: "PersonBundle:Personne:index" }

personne_show:
    path:     /{id}/show
    defaults: { _controller: "PersonBundle:Personne:show" }

personne_new:
    path:     /new
    defaults: { _controller: "PersonBundle:Personne:new" }

personne_create:
    path:     /create
    defaults: { _controller: "PersonBundle:Personne:create" }
    requirements: { method: post }

personne_edit:
    path:     /{id}/edit
    defaults: { _controller: "PersonBundle:Personne:edit" }

personne_update:
    path:     /{id}/update
    defaults: { _controller: "PersonBundle:Personne:update" }
    requirements: { method: post|put }

personne_delete:
    path:     /{id}/delete
    defaults: { _controller: "PersonBundle:Personne:delete" }
    requirements: { method: post|delete|get }
