imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        
        - MainBundle
        - PersonBundle     
        - PostBundle
        - FOSUserBundle
        - JDPhpProjectAnalyzerBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


# FosUser Configurationlogin
fos_user:
    db_driver: orm #
    firewall_name: main
    user_class: Framelab\Bundle\UserBundle\Entity\User
    

fr3d_ldap:
    driver:
        host:                   %ldap_host%
        port:                   %ldap_port%
        username:               %ldap_username%
        password:               %ldap_password%
        baseDn:                 %ldap_baseDn%
        useSsl:                 %ldap_useSsl%
        bindRequiresDn:         %ldap_bindRequiresDn%
        accountFilterFormat:    %ldap_accountFilterFormat%
    user:
        baseDn:     OU=Utilisateurs, DC=exchange, DC=po, DC=fr     # %ldap_dn%

jd_php_project_analyzer:
    title:          Frame Lab
    description:    It's a ouaaaouhh project !

    gitRepositoryURL: https://github.com/jdlabails/PhpProjectAnalyzerBundle

    # chemin d'analyse
    srcPath : /home/jd/Dev/framelab/src/Bundle
    
    # métrique quantitative
    count : true

    # métrique qualité copy-paste
    cpd : true

    # métrique qualité code sniffer
    cs :
        enable: true
        standard: Symfony2

    # métrique qualité php depend
    depend : false

    # métrique qualité php loc
    loc : true

    # métrique qualité mess detector
    md :
        enable: true
        rules:
            cleancode: true
            codesize: true
            controversial: true
            design: true
            naming: true
            unusedcode: true

    # possiblité de généré la phpdoc
    docs : true

    # tests unitaires et fonctionnels
    test :
        enable: true
        lib : phpunit       # phpunit || atoum
        phpunitTestSuite : Retweeter
        phpunitTestConfig: /home/jd/Dev/framelab/app/phpunit.xml.dist
#        atoumPath : /home/smith/www/projectX/vendor/bin/atoum
#        atoumTestDir : /absolute/path/to/your/test/dir

    # score
    score:
        enable:         true
        csWeight:       100     # between 0 and 100, weighting of code sniffer
        testWeight:     100     # between 0 and 100, weighting of testing
        locWeight:      100     # between 0 and 100, weighting of code coverage  

m6web_guzzlehttp:
    clients:
        default: ~
        twitter:
            base_uri: "https://api.twitter.com/1.1/"

#hwi_oauth:
#
#    # optional FOSUserBundle integration
#    fosub:
#        # try 30 times to check if a username is available (foo, foo1, foo2 etc)
#        username_iterations: 30
#
#        # mapping between resource owners (see below) and properties
#        properties:
#            github: githubId
#            google: googleId
#            facebook: facebookId
#            my_custom_provider: customId
#
#    # if you want to use 'connect' and do not use the FOSUB integration, configure these separately
#    connect: ~
##        confirmation: true # should show confirmation page or not
##        registration_form_handler: my_registration_form_handler
##        registration_form: my_registration_form
##        account_connector: my_link_provider # can be the same as your user provider
#
#    # optional HTTP Client configuration
#    http_client:
#        timeout:       5
#        verify_peer:   true
#        ignore_errors: true
#        max_redirects: 5
#
#    # allows to switch templating engine for bundle views
#    #templating_engine: "php"
##    resource_owners:
##        twitter_jd:
##            type:                twitter
##            client_id:           BUxAaFujE8GRrOplX8SZQa7qv
##            client_secret:       ekIB1P20d1zLf33poMP6kIRgTWgLQtLVMnA2h04hQr12sZU3sN
##            options:
##                include_email: true
##                
#    # list of names of the firewalls in which this bundle is active, this setting MUST be set
##    firewall_names: [main]
#
#    # an optional setting to configure a query string parameter which can be used to redirect
#    # the user after authentication, e.g. /connect/facebook?_destination=/my/destination will
#    # redirect the user to /my/destination after facebook authenticates them.  If this is not
#    # set then the user will be redirected to the original resource that they requested, or
#    # the base address if no resource was requested.  This is similar to the behaviour of
#    # [target_path_parameter for form login](http://symfony.com/doc/2.0/cookbook/security/form_login.html).
#    # target_path_parameter: _destination
#
#    # an optional setting to use the HTTP REFERER header to be used in case no
#    # previous URL was stored in the session (i.e. no resource was requested).
#    # This is similar to the behaviour of
#    # [using the referring URL for form login](http://symfony.com/doc/2.0/cookbook/security/form_login.html#using-the-referring-url).
#    # use_referer: true
#
#    # here you will add one (or more) configurations for resource owners
#    # and other settings you want to adjust in this bundle, just checkout the list below!