twitter_retweet_stat:
    resource: "@TwitterBundle/Controller/RetweetStatController.php"
    type:     annotation

twitter_retweeter:
    resource: "@TwitterBundle/Controller/RetweeterController.php"
    type:     annotation

jd_php_project_analyzer:
    resource: "@JDPhpProjectAnalyzerBundle/Resources/config/routing.yml"
    prefix:   /

rate:
    resource: "@RateBundle/Resources/config/routing.yml"
    prefix:   /

post:
    resource: "@PostBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

person:
    resource: "@PersonBundle/Resources/config/routing.yml"
    prefix:   /person/

document:
    resource: "@DocumentBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
