security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_DEV:         ROLE_USER
        ROLE_ADMIN:       ROLE_DEV
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        chain_provider:
            chain:
                providers: [fos_userbundle]
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
#        secured_area:
#            pattern:    ^/
#            form_login:
#                provider: fos_userbundle
#                login_path: /connect/
#                check_path: /login/login_check
#            anonymous:    true
#            oauth:
#                resource_owners:
#                    twitter_jd:             "/login/check-twitter"
#                login_path:        /connect
#                failure_path:      /connect
#
#                # FOSUB integration
#                oauth_user_provider:
#                    service: hwi_oauth.user.provider.fosub_bridge
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
#            fr3d_ldap:  ~
            form_login:
                provider: chain_provider
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: true
                default_target_path: /
                #login_path: /no_access # créer le controller pour renvoyer un json no access
            logout:       true
            anonymous:    true
#            oauth:
#                resource_owners:
#                    twitter_jd:             "/login/check-twitter"
#                login_path:        /login
#                use_forward:       false
#                failure_path:      /login
#
#                # FOSUB integration
#                oauth_user_provider:
#                    service: hwi_oauth.user.provider.fosub_bridge

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ppa, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/, role: ROLE_USER }         
        - { path: ^/person, role: ROLE_USER }
        - { path: ^/document/, role: ROLE_USER }
        - { path: ^/commentpost/, role: ROLE_USER }
        - { path: ^/article/, role: ROLE_USER }
        
        - { path: ^/ldap/explorer, role: ROLE_ADMIN }
        - { path: ^/ldap/rechercher, role: ROLE_ADMIN }
        - { path: ^/user, role: ROLE_ADMIN }
        
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }