rate_like:
    path:     /rate_like
    defaults: { _controller: "RateBundle:Rate:like" }

rate_like_button:
    path:     /rate_like_button/{id}/{type}
    defaults: { _controller: "RateBundle:Rate:likeButton" }
