article:
    path:     /
    defaults: { _controller: "PostBundle:Post:index" }

article_show:
    path:     /{id}/show
    defaults: { _controller: "PostBundle:Post:show" }

article_new:
    path:     /new
    defaults: { _controller: "PostBundle:Post:new" }

article_create:
    path:     /create
    defaults: { _controller: "PostBundle:Post:create" }
    requirements: { method: post }

article_edit:
    path:     /{id}/edit
    defaults: { _controller: "PostBundle:Post:edit" }

article_update:
    path:     /{id}/update
    defaults: { _controller: "PostBundle:Post:update" }
    requirements: { method: post|put }

article_delete:
    path:     /{id}/delete
    defaults: { _controller: "PostBundle:Post:delete" }
    requirements: { method: post|delete }
